- penn/dining.py
> Fix missing venues hours

- .travis.yml
- penn/__init__.py
- penn/base.py
- penn/dining.py
- penn/directory.py
- penn/laundry.py
- penn/map.py
- penn/news.py
- penn/registrar.py
- penn/transit.py
- requirements.txt
- tests/laundry_test.py
- tests/nem_test.py
- tests/transit_test.py
- tox.ini
Fixes #40 and somehow #42.
Fixed #43 as well
Also makes codebase acceptably PEP8
> Python 3 conversion

- penn/laundry.py
- tests/laundry_test.py
Much easier to read and has more rigorous testing now.
> Laundry refactor

- AUTHORS.rst
> Add AUTHORS.rst

- docs/registrar.rst
- penn/base.py
- tests/laundry_test.py
> API errors class

- .travis.yml
Automatic secure deploys to PyPI through tagged releases on GitHub
> Travis Deployment

- penn/directory.py
- requirements.txt
- tests/directory_test.py
> Standardize directory

- penn/__init__.py
- penn/studyspaces.py
- tests/studyspaces_test.py
Needs to be deployed to test functionality on penn-mobile-server
> Studyspaces

- docs/laundry.rst
- docs/library.rst
- penn/__init__.py
Will be live at http://penn-sdk.readthedocs.io/en/latest/
> Add documentation for orphaned modules

- penn/calendar3year.py
- tests/calendar_test.py
Ran into this problem while writing the penn-mobile-server endpoint.
> Dates should be strings not date objects

- penn/laundry.py
- tests/laundry_test.py
Scrapes this page: 
https://www.laundryalert.com/cgi-bin/penn6389/LMRoomUsage?CallingPage=LMRoom&Password=penn6389&Halls=0
> Laundry Usage

- penn/laundry.py
There was a bug in the update-laundry bug that caused the running counter to be broken. Quick fix.
> Fixed bug with running in laundry

- penn/laundry.py
The new variable is used by `penn-mobile-server`.
> Create hall id object array for laundry

- MANIFEST.in
- penn/data/laundry.csv
- penn/laundry.py
The front page for laundry is going away soon, so need to hardcode in the values.
> Hardcode in id/hall/location for laundry

- penn/base.py
- penn/data/laundry.csv
- penn/laundry.py
- penn/studyspaces.py
Adds additional information for the all halls and hall by id endpoints under `machines -> details`.
Does not modify the structure of existing data in order to preserve backwards compatibility with already deployed mobile applications.
```json
{
"hall_name": "Bishop White", 
"location": "Quad", 
"machines": {
"details": [
{
"id": 10, 
"status": "End of cycle", 
"time_remaining": 0, 
"type": "dryer"
}, 
{
"id": 11, 
"status": "Ready to start", 
"time_remaining": 0, 
"type": "dryer"
}, 
{
"id": 12, 
"status": "End of cycle", 
"time_remaining": 0, 
"type": "dryer"
}, 
{
"id": 13, 
"status": "In use", 
"time_remaining": 42, 
"type": "dryer"
}, 
{
"id": 14, 
"status": "In use", 
"time_remaining": 42, 
"type": "dryer"
}
...
],
"dryers": {
"offline": 0, 
"open": 7, 
"out_of_order": 0, 
"running": …
```
> Add additional laundry details

- penn/laundry.py
- requirements.txt
- tests/directory_test.py
- tests/laundry_snapshot.html
- tests/laundry_test.py
Directory tests are working again, so just uncommented them. Added mock for laundry request since the site is not externally accessible anymore.
Also added an environment variable `LAUNDRY_DOMAIN` to fix #77.
This pull request fixes #75.
> Fix laundry and directory tests

- .gitignore
- .travis.yml
- penn/__init__.py
- penn/calendar3year.py
- penn/dining.py
- penn/directory.py
- penn/studyspaces.py
- requirements.txt
- setup.py
- tests/calendar_test.py
- tests/dining_test.py
- tests/studyspaces_test.py
Fix #89, rebuild the study space API. Implements everything needed to list rooms, but currently does not have any methods for booking rooms.
Tag to version `1.6.7` once this is merged.
> Rebuild study spaces

- AUTHORS.rst
- LICENSE.txt
- docs/calendar.rst
- penn/__init__.py
- penn/base.py
- penn/laundry.py
- penn/studyspaces.py
- requirements.txt
- setup.py
- tests/studyspaces_test.py
- Add `/studyspaces/book` POST endpoint to book a room.
- Add more documentation to various functions.
- Update dates, add self to authors :)
Should be tagged to `v1.6.8` after this pull request is merged.
> Add booking endpoint for studyspaces

- docs/fitness.rst
- docs/index.rst
- penn/fitness.py
- tests/fitness_test.py
Add API to retrieve Penn Recreation usage data.
> Add fitness API

- penn/__init__.py
- penn/wharton.py
Example result:
```
{
"reservations": [
{
"booking_id": 100648,
"date": "Feb 06, 2019",
"endTime": "9 p.m.",
"location": "JMHH G61",
"startTime": "8:30 p.m."
},
{
"booking_id": 100661,
"date": "Feb 06, 2019",
"endTime": "10 p.m.",
"location": "JMHH 378",
"startTime": "9:30 p.m."
}
]
}
```
Error handling for bad session ID:
```
{
"error": "Wharton Auth Failed. Session ID is not valid."
}
```
> Created Wharton Module with Current Reservations Scraping

- penn/wharton.py
Added Wharton GSR booking deletion
> Wharton GSR Delete

- .travis.yml
- penn/__init__.py
- penn/studyspaces.py
- tests/registrar_test.py
- tests/studyspaces_test.py
- tox.ini
Wrapper for libcal bookings and room info endpoints.  Room info endpoint is needed to include the room name in the booking JSON.
```
{
"reservations": [
{
"booking_id": "111895",
"fromDate": "2019-02-19T23:30:00-05:00",
"gid": 1,
"info": null,
"lid": 1,
"name": "JMHH F47",
"service": "wharton",
"toDate": "2019-02-20T00:00:00-05:00"
},
{
"booking_id": "111884",
"fromDate": "2019-02-20T00:00:00-05:00",
"gid": 1,
"info": null,
"lid": 1,
"name": "JMHH F47",
"service": "wharton",
"toDate": "2019-02-20T00:30:00-05:00"
},
{
"booking_id": "111885",
"fromDate": "2019-02-20T00:30:00-05:00",
"gid": 1,
"info": null,
"lid": 1,
"name": "JMHH F46",
"service": "wharton",
"toDate": "2019-02-20T01:00:00-05:00"
},
{
"booking_id": "cs_JpED9ZhX",
"fromDate": "2019-02-18T23:30:00-05:00",
"gid": 1889,
"info": { …
```
> Retrieve reservations and room info

- penn/wharton.py
- setup.py
- tests/nem_test.py
/studyspaces/availability/1 JSON: 
categories: [
{
cid: 1,
name: "Huntsman Hall",
rooms: [
{
capacity: 5,
lid: 1,
name: "GSR 241",
room_id: 94,
times: [
{
available: true,
end: "2019-02-08T18:30:00-05:00",
start: "2019-02-08T17:00:00-05:00"
},
{
available: true,
end: "2019-02-08T18:30:00-05:00",
start: "2019-02-08T17:30:00-05:00"
},
{
available: true,
end: "2019-02-08T18:30:00-05:00",
start: "2019-02-08T18:00:00-05:00"
},
> integrated wharton endpoint

- penn/__init__.py
- penn/studyspaces.py
- penn/wharton.py
- setup.py
Added optional timeouts to Wharton & Libcal Reservations
> GSR Reservation Timeouts

- penn/studyspaces.py
- penn/wharton.py
> GSR Timeouts Bug Fix
